@HostAddress = https://localhost:7064

GET {{HostAddress}}/matches/seers/76244189/matches?date=2026-06-17
Accept: application/json

###

GET {{HostAddress}}/predictions/matches/1/seers/6
Accept: application/json

###

GET {{HostAddress}}/predictions/db-path
Accept: application/json